### ISSUE TITLE
Double check all links are correct

### ISSUE THREAD

**Issue by paigerodeghero** [SEmotion/2021#9]
Todo after the website is deployed.

**Comment by okarras** [comment]
The tabs "Call for Papers", "Organization" and "Program" contains "Social Media - Tweets by SEmotion" two times.

**Comment by okarras** [comment]
Linking error: The link to the previous workshop SEmotion 2020 links to SEmotion 2019.

**Comment by makayla-moster** [comment]
> Linking error: The link to the previous workshop SEmotion 2020 links to SEmotion 2019.

Fixed.

**Comment by makayla-moster** [comment]
> The tabs "Call for Papers", "Organization" and "Program" contains "Social Media - Tweets by SEmotion" two times.

Fixed.

**Comment by paigerodeghero** [comment]
@makayla-moster and @okarras  -- Once you both have played around with it for a few minutes and don't find any errors, feel free to close this issue.  When we find bugs, we can create a new issue if need be.

**Comment by okarras** [comment]
I checked all links. I did not find any other linking error. I think we can close this issue.

I cannot close the issue. I do not have the rights.
